blank_issues_enabled: false
contact_links:
  - name: Shared Kingdom README
    url: https://github.com/your-org/shared-kingdom#readme
    about: Review the project overview and setup instructions before opening an issue.
